- bootkit/main.go
- noname.yaml
- tink-docker/main.go
This provides the capability to enable reboots from another action by writing `/worker/reboot` to the `/worker` volume.
> Fixes reboots in noname

- .gitignore
- Makefile
- README.md
- bootkit/go.mod
- tink-docker/go.mod
- tinkie.yaml
Fixes #15.
There are some things that need to be adjusted before merging this.
> Rename noname to tinkie

- .envrc
- .gitignore
- shell.nix
Mostly makes the shell.nix better by avoiding duplicating all of the linuxkit derivation in favor of overriding the linuxkit src bits.
Better to override only the minimal bits. Also adds direnv's .envrc file so matches other tinkerbell repos and brings much happiness.
Everything still works.
Save .01s when starting to develop here, each time!
> nix: misc/nit fixes

- .mergify.yml
Fixes the mergify config from the recent default branch rename from master -> main.
Sets us up for mergify to merge again.
> mergify: Update PR rule condition to base=main

- hook.yaml
`hook.yaml` was referencing the wrong image name
Fixes path to the image on quay.io
Fixes: #
I have:
> Fixes path to correct image

- .github/workflows/ci.yaml
- .gitignore
- Makefile
- shell.nix
Linuxkit has removed the `-disable-content-trust` flag
* removed deprecated linuxkit flag from Makefile
* Added clean Make target
* Added build dirs to gitignore
* Fixed broken CI from #48
I couldn't get the previously used version of linuxkit to build.
I built a hook image locally and booted a Tink worker with the latest version of linuxkit
Users can use and build a with a newer version of linuxkit
I have:
> Bumped version of linuxkit

- hook.yaml
Added missing mounts for dhcpd and ntpd to work
dhcpcd and ntpd were both failing without the supplied mounts.
I booted a tink worker on a bare-metal host and 
I couldn't get networking or ntp without the supplied mounts.
I have:
> Fixed missing mounts in dhcpcd and ntpd

- .golangci.yml
- Makefile
NOTE: This is using an experimental branch of https://github.com/tinkerbell/lint-install that works on projects with multiple Go modules.
> Add 'make lint' rule to run golangci-lint, shellcheck, hadolint

- Makefile
- bootkit/main.go
- tink-docker/main.go
Fix all the errors reported from lint-install
cd tink-docker; ../out/linters/golangci-lint-v1.42.0 run
cd bootkit; ../out/linters/golangci-lint-v1.42.0 run
Fix Makefile error.
Fixes: #
Test:
make image
make dev
I have:
> Fix errors from lint-install run.

- CONTRIBUTING.md
- Makefile
- README.md
Update all refs from master -> main
> Prepare for default branch rename

- hook.yaml
- hook_debug.yaml
This adds an `alias` to hook.yaml and hook_debug.yaml, that makes debugging much more simple.
Remembering the `ctr` command is nigh on impossible. 
Fixes: #
The pain of trying to remember the `ctr` flags :-)
I have:
> Adds an alias to make debugging easier!

- hook_debug.yaml
Adds a oneshot DHCP call when hook starts
This ensures that networking configuration exists BEFORE services start.
Fixes: #
I have:
> Add a oneshot DHCP call when hook starts

- tink-docker/main.go
Instead of immediate failure, we now have a retry mechanism in the event DHCP is slow
Instant failure happens if the network takes a little bit of time to come up.. this adds a retry and sleep etc.
Fixes: #
I have:
> Adds retry instead of immediate failure

- .github/workflows/kernel-push.yaml
- .github/workflows/push.yaml
Avoids logging into quay for dependabot builds.
Fixes #92
Dependabot PRs are different than other non-contributor PRs in that the branch comes from this repo, which normally allows the secret to be available for CI yet the builds still fail (see [1], [2]). It seems that GitHub does not make secrets available for these PRs as yet another special case [3]. If we skip logging in to quay for dependabot then we side step this all together.
Dependabot pushes/PRs can be recognized by the github.actor value according to the GitHub docs [3].
[1]: https://github.com/tinkerbell/hook/pull/89
[2]: https://github.com/tinkerbell/hook/pull/95
[3]: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#handlin …
> Don't try to login to quay if a push is made by dependabot

- .github/workflows/push.yaml
Avoids pushing to quay if the PR/push originates from dependabot.
We skipped logging in to quay.io when github.actor is dependabot in [#96] but
did not check if any pushes were attempted. This change will avoid that
failure.
This was missed in the subsequent dependabot PRs [#89] and [#95] because there
was no branch protection setup and I added the ready-to-merge label so mergify
merged it :(. I've added branch protection to require the actions to pass.
[#89]: https://github.com/tinkerbell/hook/pull/89
[#95]: https://github.com/tinkerbell/hook/pull/95
[#96]: https://github.com/tinkerbell/hook/pull/96
CI
> ci: Only push to quay if github.actor is not dependabot

- hook.yaml
- kernel/Makefile
- kernel/config-5.10.x-aarch64
- kernel/config-5.10.x-x86_64
This PR updates the hook kernel to 5.10.85 and could maybe close #90. Earlier 5.10.x kernel versions, such as 5.10.57 which was the previously released kernel for hook, seemed to have a bug in the `igc` module that prevented certain NICs from functioning. Later kernel versions fixed this issue.
We need to discuss longer term plans for supporting hook though. Hook had not seen a kernel update for many months, but meanwhile new hardware requiring support continues to come onto the market. We should formulate a plan for moving hook to the next LTS kernel which is 5.15 and also a release cadence as new kernels release upstream.
Fixes: #90
**Note:** this still needs to be run through the standard tinkerbell CI tests.
This has been tested with a single device ([Minisforum …
> Update hook kernel to 5.10.85

- bootkit/main.go
This PR adds `/proc/cmdline` parsing for `tinkerbell_tls` and `tink_worker_image`:
Boots now has the ability to not pass kernel commandline args for a registry. When not passing registry info we will need to know the location of the tink worker container image. This is handled with the `tink_worker_image` kernel commandline arg.
Tink server now has the ability to run without TLS. The `tinkerbell_tls` kernel commandline arg is used to determine this. This value is parsed and passed along to the Tink worker.
Fixes: #
I have:
> Add /proc/cmdline parsing for tinkerbell_tls and tink_worker_image:

- hook.yaml
I was experiencing the same issue as [here](https://github.com/tinkerbell/hook/pull/79), but removing all the bind mounts didn't resolve it for me. However, adding the bind mounts back and creating the `/var/lib/dhcpcd` directory was the only way for me to get the interfaces to start working. With these changes the dhcpcd.log files were error free.
Hey @thebsdbox. If you have any cycles, I'd be very interested to know if the `main: pidfile_lock: Permission denied` error still happens for you with this PR.
Update dhcpcd onboot and service containers:
Network interfaces were not coming up. Logs showed "`main: pidfile_lock: Permission denied`". Adding the bind mounts and directory creation resolved the issue.
Fixes: #
I have:
> Update dhcpcd onboot and service containers:

- hook.yaml
- tink-docker/Dockerfile
- tink-docker/go.mod
- tink-docker/main.go
- tink-docker/main_test.go
Currently, the only way to see container logs for workflows is to access the console of a machine. This makes troubleshooting difficult. This PR sends the tink-worker and workflow container logs back to aSyslog host.
Fixes: #81 
Fixes: #86 
I have:
> Send container logs to syslog server

- .github/workflows/push.yaml
Uses a step to set the commit shortid as an output instead of using GITHUB_SHA.
We can't use GITHUB_SHA in yaml blocks, in the Build and push * and upload-artifact steps.
Ran `act` locally (with some modifications to avoid logging into quay/attempting to push).
Builds work again.
> Fix image builds on main branch

- .github/workflows/ci.yaml
- hook.yaml
- Makes CI green again by avoiding attempting to push the linuxkit images via `make deploy` which was deleted.
- Removes the dbg only binding of /etc/daemon.json which breaks hook-docker since it ends up being mounted read-only.
Fixes CI and dbg runs.
CI fix should just work.
I've been running with the daemon.json drop in a different branch and thought it was in branch for #130. 
CI is :heavy_check_mark: not :x: which makes us all feel warm and fuzzy.
dbg builds are actually useful and work.
> Fixes for #130 which was fixes for #105

- hook-bootkit/main.go
Now that tink never serves /cert we don't need to handle it.
Cleaning up unused code/tech-debt.
Ran a workflow run.
> Drop grpc_cert_url param

- .github/workflows/ci.yaml
Uses the correct path to the build files when passing them to upload-artifact so that the files are actually uploaded. 
Files weren't being uploaded.
From my fork.
They can fetch files built by official CI instead of being required to build locally.
> Rework use of actions/upload-artifact

- .github/workflows/kernel-push.yaml
Avoids building the kernel for tag pushes.
The kernel builds are currently filtering the events that cause the build depending on the path of files changed. The path filter is not evaluated for tag pushes though. This causes the kernel to be re-pushed on tags which is unexpected and confusing. I'd rather avoid confusion in the kernel build/push process if possible.
> ci: Limit the kernel push only to branch pushes

- .github/settings.yml
Hello. I would like to request moving from reviewer to approver role. I am looking for a sponsor from either @mmlb or @thebsdbox. Please and thank you.
Requirements:
PR Reviews
https://github.com/tinkerbell/hook/pull/98
https://github.com/tinkerbell/hook/pull/89
https://github.com/tinkerbell/hook/pull/130
PR merges
https://github.com/tinkerbell/hook/pull/118
https://github.com/tinkerbell/hook/pull/117
https://github.com/tinkerbell/hook/pull/116
https://github.com/tinkerbell/hook/pull/115
https://github.com/tinkerbell/hook/pull/59
Sponsor Request from
@mmlb 
@thebsdbox
> Request for Approver Role

- hook-bootkit/go.mod
- hook-bootkit/go.sum
- hook-bootkit/main.go
Image pull retry for tink-worker image
There could be races where linuxkit network or dns may not have been
fully set up and functional yet and image pull fails because of that.
Fixes: #
Implement image pull retry loop for tink-worker image. This loop attempts an image pull every 5 seconds, upto 10 times
Tested by re-running a full provisioning workflows on bare metal server and simulate image pull failures artificially to test out the retry logic.
I have:
> Tink worker image pull retry

- files/dhcp.sh
- files/dhcpcd.conf
- files/vlan.sh
- hook.yaml
This enables creating VLAN interfaces based on the `vlan_id=` value in `/proc/cmdline`. No VLAN interface will be created if `vlan_id=` does not have a value.
This enables trunk vlan support across the Tink stack. https://github.com/tinkerbell/proposals/blob/main/proposals/0030/README.md
Fixes: #
I have:
> Create VLAN interface before DHCPing:

- hook-bootkit/main.go
- hook-docker/main.go
- hook-docker/main_test.go
- lint.mk
- shell.nix
This removes unused code making network calls to Hegel and updates the linter version.
Fixes: #110 
I have:
> Remove unused metadata network call

- hook-bootkit/main.go
- hook-docker/main.go
Add support for pulling docker images and specifically the tink-worker image via a proxy by configuring appropriate proxy variables via Boots.
Currently a user cannot use a proxy to pull tink-worker and container images for workflows. This PR enables proxy support for this. A user will have to pass HTTP_PROXY, HTTPS_PROXY and NO_PROXY to Boots as cli args or environment variables. These values in Boots, [extra kernel args](https://github.com/tinkerbell/boots/blob/c92674c5f39f7005602bc6882afd035dc0f13d0c/cmd/boots/main.go#L371), get populated in Hook's `/proc/cmdline` file. hook-bootkit and hook-docker will pick up those variables and set them as an environment variables in order to pull tink-worker and workflow images from a proxy server. 
Fixes: #
I have tested this changes by creating a …
> Add proxy support for hook-bootkit and hook-docker

- files/dhcp.sh
Check if `vlan_id=` exists and if it has a value. This allows for an empty `vlan_id=` value.
Fixes: #
I have:
> Update vlan checking:

- .github/workflows/ci.yaml
This works around an issue where a change in the `kernel/` directory doesn't trigger the required validation check in GitHub.
Fixes: #145 
I have:
> Run CI jobs for all directories:

- Makefile
- RELEASING.md
- hook.yaml
This allows us to know at runtime the version of HookOS. Also, modified the prompt to contain the version so that when sharing screenshots to debug it will be clear the Hook version.
Turned down the kernel.printk log level to warning (4) so that the console Getty doesn't get messy with kernel messages. Better UX (hopefully). A side effect of this is that we won't see messages anymore on the console when workflow action containers run. Syslog messages will still be sent to Boots.
Fixes: #176 
I have:
> Add os-release file

- files/dhcp.sh
This fixes an issue where "vlan_id" is a substring. For example: "thisisavlan_id=123". This example will be treated as if the vlan_id was not set at all.
Fixes: #180 
I have:
> Update sed command for getting vlan_id from cmdline:

- .github/workflows/ci.yaml
This makes it safer for users to consume Hook tarballs. Will also help the user experience in the charts repo.
Fixes: #168 
I have:
> Add checksum file creation to releases:

- hook-docker/Dockerfile
kexec-tools has been promoted from edge/testing to edge/community. This PR updates the repository in the hook-docker Dockerfile.
For reference: https://git.alpinelinux.org/aports/commit/community/kexec-tools/APKBUILD?id=eccd9de1410cd384891105da4bedb05b7db44744
Builds will fail because the kexec-package cannot be installed:
```
#7 2.121 ERROR: unable to select packages:
#7 2.121   kexec-tools (no such package):
#7 2.121     required by: world[kexec-tools]
------
Dockerfile:8
--------------------
6 |     FROM docker:24.0.4-dind
7 |     RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
8 | >>> RUN apk update; apk add kexec-tools
9 |     COPY --from=dev /hook-docker .
10 |     ENTRYPOINT ["/hook-docker"]
--------------------
error: failed to solve: process …
```
> Update apk repository for kexec-tools

- hook-bootkit/main.go
- hook-docker/main.go
Handle kernel parameters with `=` in their value. This enables kernel parameters to be correctly parsed.
Fixes: #
I have:
> Handle kernel parameters with `=` in their value:

- bash/kernel.sh
- forgot a `|| true` in there somehow
> build: fix: don't ignore kernel push failures

- bash/hook-lk-containers.sh
- bash/kernel/kernel_armbian.sh
rework image naming.
Fixes: #
I have:
> rework image naming in ci

- .github/workflows/build-all-matrix.yaml
> Update GitHub release with release notes

- bash/kernel/kernel_armbian.sh
- previous approach only took the 2nd dash-field, which is not enough to uniquely identify kernels
- avoid `uefi-x86-edge` and `uefi-arm64-edge` both competing for `uefi`
> build: armbian kernels: use inventory_id (sans "armbian-" prefix) in kernel tag name

- bash/hook-lk-containers.sh
- This reverts commit 69a4c8725cd0a3585e40188ac82b262984c991f4:
> "The service containers we build shouldnt use arch in the tags. This way the same tag will have mulitple archs at the registry layer."
- this isn't really true, as can be seen from the --platform argument to buildx; also the GHA matrix'es are split per-arch
- effectively, we had random arch (but not both) in each tag, depending on build speed/order in GHA
- causes `Error creating 000-rngd1: fork/exec /usr/bin/runc: exec format error` (and many others) depending on luck or lack thereof
> Revert "Dont use arch in container image tag:"

- images/containerd/Dockerfile
- images/containerd/etc/containerd/config.toml
- linuxkit-templates/hook.template.yaml
For some reason I was seeing issues with the 6.6 kernel and ttys when they are not explicitly set in the linuxkit yaml. Also with the 6.6 kernel, I was seeing issues with the ctr command and character encoding or something similar. I was getting a lot of weird character when using it. Moving to nerdctl resolves this issue. Nerdctl is also a lot more user friendly in general. Also, the getty container was getting permission denied issues when trying to mount devices. Explicitly adding a block devices to the linuxkit yaml resolved this.
Fixes: #
I have:
> Fix ttys, fix device mounting issue in getty, add nerdctl

- bash/hook-lk-containers.sh
Because of the way CI is built (2 self-hosted runners), CI was not pushing container images when building on main. This was because PR's would build the images and the would be locally in the Docker cache. Then when main ran, hook-lk containers.sh would run and see that the image existed in the local Docker cache already and stop before pushing.
Fixes: #
I have:
> Push container images properly:

- bash/common.sh
- bash/json-matrix.sh
- bash/kernel/kernel_armbian.sh
- bash/linuxkit.sh
- images/hook-bootkit/Dockerfile
- images/hook-containerd/Dockerfile
- images/hook-docker/Dockerfile
- images/hook-mdev/Dockerfile
- images/hook-runc/Dockerfile
- linuxkit-templates/hook.template.yaml
> - recent userspace additions took the initramfs size near or over the 900mb mark for certain kernels.
> - initramfs (gzipped cpio) is uncompressed by bootloader and mounted on tmpfs by kernel.
> - tmpfs allows only 50% of physical RAM by default, and default can't be changed easily.
> - slim down both the userspace (by stripping / removing some / etc) and the Armbian kernels (by removing modules)
> - with those we're back below 900mb uncompressed again, and the default x86 hook tarball is down from 223 to 180mb compressed.
> - add a check for uncompressed cpio size at 900mb; warn in GHA if it is ever hit again.
> - also includes: fixes for ttyAML consoles, better logging, some dev/debug options used for batch
> 
> note: review is easier if done commit-by-commit; sent a large batch due …
> rpardini's May'24 fix batch: slim for 2Gb RAM devices

- linuxkit-templates/hook.template.yaml
- ttyUSB0 is useful when handling machines without onboard tty, eg, laptops (use a ttl-dongle pair)
> hook: add ttyUSB0/ttyUSB1 to getty consoles list

- images/hook-mdev/Dockerfile
- images/hook-mdev/persistent-storage
- images/hook-mdev/persistent-storage.sh
- original persistent-storage from upstream Alpine:
- source https://gitlab.alpinelinux.org/alpine/mdev-conf/-/blob/master/persistent-storage?ref_type=heads
- revision a21d1053dd5ca37538b0435d66c58a30cb273658
- this is being added as reference for future rebases; it will be shellfmt'ed and modified in later commits
- simple rename & shellfmt; separate commit for easy future rebasing
- this is still not-even-close to systemd's udev, but should at least add _something_ to by-id when Alpine's mdev wouldn't
- if device reports model and serial, all was/is good;
- introduce:
- if model or serial missing, try parsing them from wwid;
- falls back to using the sanitized wwid as serial if parsing fails
- last resort: falls back to using 'noserial' as serial for devices that only have a model.
- …
> hook-mdev: better `/dev/disk/by-id` via custom mdev script for wwid parsing and fallbacks

- images/hook-mdev/persistent-storage.sh
- some hardware vendors have literal `\0` (backslash-zero) instead of proper null bytes in wwid
- encoding that in YAML is painful, and systemd udev trims those out
> hook-mdev: `persistent-storage`: further sanitize model/serial parsed from wwid

- .github/workflows/build-all-matrix.yaml
- bash/json-matrix.sh
- previously, it only used GHA cache for builds running on GH-hosted runners
- this now enables it for all builds, even on self-hosted runners
- next few builds might still fail, but further ones will have a cache (we've `save-always: true`) and should eventually work
> build: gha: always use GHA cache for Linuxkit Cache in hopes of diminishing DockerHub pull-rate limits trouble

- README.md
- bash/kernel.sh
- bash/kernel/kernel_default.sh
When the `kernel-releases.json` is updated, which is pretty frequent, a new point release will be available and require Users to build the kernel. With this commit, `USE_LATEST_BUILT_KERNEL` allows a User to build HookOS without having to build the kernel. This is done by getting the latest point release from `quay.io/tinkerbell/hook-kernel` image tags.
Fixes: #
I have:
> Allow building HookOS from existing kernel image:

- linuxkit-templates/hook.template.yaml
- Rockchip uses ttyS2 as debug console by default on mainline
> hook: handle `/dev/ttyS2` console

- .github/workflows/build-all-matrix.yaml
- build.sh
v0.9.0 -> v0.9.1
Fixes: #
I have:
> Bump version

- README.md
- bash/linuxkit.sh
Linuxkit also offers an option to build kernel as an iso file. Update the build script to be able Hook as an ISO. 
Apart from the default build, this change provides the users to be able to mount Hook as an ISO and boot using the virtual media option. 
Fixes: #
Set `LINUXKIT_ISO` to true and built hook as an ISO. Mounted the ISO on a Dell R340 as a virtual media device and booted using the ISO. As this flow kicks in only when the above env var is set, it should affect any existing user workflow. 
If this gets approved, I will update the Readme appropriately to document the option to build as an ISO.
I have:
> Update build script to facilitate iso builds

- .github/workflows/build-all-matrix.yaml
- bash/hook-lk-containers.sh
- bash/inventory.sh
- bash/json-matrix.sh
- bash/kernel.sh
- bash/kernel/kernel_armbian.sh
- bash/kernel/kernel_default.sh
- bash/linuxkit.sh
- build.sh
- use inventory and output into json matrix
- introduce `hook_template_vars` dict (KEY=value)
- with `HOOK_VERSION`, `HOOK_KERNEL_IMAGE` et al directly
- remove the nameref from `build_hook_linuxkit_container`, instead set directly in the `hook_template_vars` dict (`HOOK_CONTAINER_BOOTKIT_IMAGE` et al)
- derive the envsubst dollar-prefixed list and the actual vars from the dict
- before: refer to the variable 3 times (settage, export, dollar)
- after: add variable to dict (once)
- dead code for `kernel_id_to_use` (we're using …
> batch of small fixes and enhancements - late december'2024

- .editorconfig
- .github/workflows/build-all-matrix.yaml
- bash/common.sh
- bash/docker.sh
- bash/hook-lk-containers.sh
- bash/kernel.sh
- bash/kernel/kernel_armbian.sh
- bash/kernel/kernel_default.sh
- bash/linuxkit.sh
- bash/shellcheck.sh
- build.sh
- images/hook-containerd/Dockerfile
- images/hook-runc/Dockerfile
- kernel/.dockerignore
- kernel/Dockerfile
> further enhancements:
> - can now build (and develop) Hook for any arch under any arch, including for amd64 under Darwin arm64
> - full support for building on macOS+brew, including on arm64
> - added `shellfmt` tool and bash code format enforcing on CI (in addition to shellcheck)
> - avoid pulling skopeo image over and over again
----
- for consistent bash formatting
- include an .editorconfig for IDE's
- if on macOS+brew:
- detects missing deps and installs them with brew
- exports PATH with brew-based GNU versions first
- coreutils, gnu-sed and gnu-tar included
- to squash recent BuildKit warnings
- can help with some edge cases
- this only affects Armbian kernel flavours
- avoids pulling if found in local cache
- since we now use the local tag
- building the Armbian kernels would …
> batch of fixes and enhancements - early january'2025

- images/hook-docker/main.go
hook-docker: fix: last kernel cmdline option would have a newline
Example:
```
(ns: getty) HookOS 0.10.0:/var/log# cat -A /proc/cmdline
coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_headphones=0 cgroup_disable=memory numa_policy=interleave snd_bcm2835.enable_hdmi=0  smsc95xx.macaddr=DC:A6:32:EC:8B:49 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=tty1 console=ttyAMA0,115200 loglevel=7 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory worker_id=rpi tink_worker_image=ghcr.io/tinkerbell/tink-agent:latest grpc_authority=tinkerbell:42113 tinkerbell_tls=false syslog_host=tinkerbell$
```
Leading to:
```
tail -f /var/log/hook-docker.log
<...snip...>
failed to start daemon: failed to set log opts: failed to set log opts: parse "udp://tinkerbell\n:514": net/url: …
```
> hook-docker: fix: last kernel cmdline option would have a newline

- .gitignore
- bash/bootable-media.sh
- bash/bootable/armbian-u-boot.sh
- bash/bootable/fat32-image.sh
- bash/bootable/grub.sh
- bash/bootable/rpi.sh
- bash/common.sh
- bash/inventory.sh
- bash/json-matrix.sh
- bash/kernel.sh
- bash/kernel/kernel_armbian.sh
- bash/kernel/kernel_default.sh
- bash/shellcheck.sh
- build.sh
- kernel/Dockerfile
>  "build and write bootable media image to SDCard/eMMC/USBkey/etc, configure kernel params, then use Tinkerbell to provision a separate NVMe/SATA/USB disk, all PXE and Smee-free"
- "L3" provisioning for small (and big) machines
- **WiP**; **RFC**.
- Still missing:
- `0README.txt` generation for each variant
- Taking `TINK_SERVER`/`TINK_GRPC_PORT`/`TINK_WORKER_IMAGE`/`MAC` vars/params and presetting in grub.cfg/cmdline.txt/extlinux.conf for self-builder's convenience
- docs (ofc; at least the self-builder part, user-facing should go into `0README.txt`)
- CI (GHA) -- I've this ready, but I'm witholding it to prove the everything else still works without changes
- Some refactor of the temporary-Dockerfile for fat32/mtools that is being abused for the u-boot specific `mkimage`
---
How to …
> Hook `bootable` media for amd64/arm64 UEFI + RPi 3/4/5 + Rockchip/Amlogic u-boot

- images/hook-bootkit/main.go
Similar to #262 but for hook-bootkit.
> hook-bootkit: fix: last kernel cmdline option would have a newline

- bash/bootable-media.sh
- bash/bootable/armbian-u-boot.sh
- bash/bootable/grub.sh
- bash/bootable/rpi.sh
- bash/common.sh
- bash/linuxkit.sh
- build.sh
> Some logging cleanup. 
> Take env/params and consistently add them to all bootloader configs (grub.cfg / extlinux.conf / boot.scr / cmdline.txt); vars should be consistent with the qemu-run invocation
> No, there is _still_ no `README.txt` generation in here. Coming up.
> No, no CI changes yet. This is all focused on building bootable images manually, for now.
- using `fill_array_bootable_tinkerbell_kernel_parameters()`
- using `fill_array_bootable_tinkerbell_kernel_parameters()`
- using `fill_array_bootable_tinkerbell_kernel_parameters()`
- this reads variables and produces kernel command line for all bootables
- it defaults to a bare `tinkerbell` hostname, but that can be overridden
with `TINK_SERVER` var/param
- `grpc_authority=tinkerbell:42113`
- `syslog_host=tinkerbell`
- usage: …
> bootable: cleanups; config grub.cfg/extlinux.conf/cmdline.txt via environment during build

- .github/workflows/build-all-matrix.yaml
- linuxkit-templates/hook.template.yaml
This puts the /run data from udev into the root filesystem as opposed to just the udev container filesystem. This is needed because other containers need access to this data.
Fixes: #
I have:
> Mount Host /run into udev onboot container:

- .gitignore
- bash/hook-lk-containers.sh
- images/hook-acpid/Dockerfile
- linuxkit-templates/hook.template.yaml
This service allows HookOS to react to ACPI events. Useful for things like `ipmitool chassis power soft`.
Fixes: #
I have:
> Add acpid service:

- .github/workflows/build-all-matrix.yaml
- build.sh
The v0.11.0 release did not have the version updated. This bumps to v0.11.1 in preparation for a new tagged release.
Because the version was not bumped in the v0.11.0 tag, HookOS is still showing v0.10.0 when booting up.
Fixes: #
I have:
> Bump version:

- .github/workflows/build-all-matrix.yaml
- bash/hook-lk-containers.sh
- bash/json-matrix.sh
- bash/kernel.sh
- kernel/Dockerfile
The `debian:stable` container image, combined with the packages we install for building the kernel, doesn't include Make anymore, so we explicitly add it. Also, move to CNCF GitHub Action runners as the self-hosted runners in Equinix Metal are going away with the Equinix Metal sunset.
Fixes: #
I have:
> Fix kernel builds; Migrate ci runners
